### PR TITLE
remove unnecessary dependencies

### PR DESCRIPTION
**Pull request by metal-oopa**
The following dependencies were unnecessary: 

1. "xtend": "^4.0.1"
2. "d3-v6-tip": "^1.0.9"
3. "d3-tip": "v0.9.1"
4. "ify-loader": "^1.1.0"

So, I have removed them from the package.json file as requested in https://github.com/GumusLab/clustergrammer/issues/8#issue-1363623599.

### CODE REVIEW

**Comment by moromis** [comment]
Just out of curiosity, how did you determine that they are unused? Just want to make sure that none are like a peer dependency or anything.

**Comment by metal-oopa** [comment]
I wrote a python script to scrape all the imported packages from all the JS/TS files.

Then, I checked all the packages and compared them with package.json and yarn.lock files.
These dependencies were not imported into any of the files. That's how I determined that they were unused.

"normalized-interaction-events" also was not imported into any file, but it had a dependency- "event-emitter" that was being used in src/cameras/functions/customCamera2D. So, I did not remove it.

**Comment by moromis** [comment]
@metal-oopa in your opinion do you think maybe we should remove `normalized-interaction-events` and add `event-emitter` then?

**Review by moromis — APPROVED** [review]
@metal-oopa  Approved contingent on removing `normalized-interaction-events` and adding `"event-emitter": "^0.3.5"` -- thanks!

**Comment by moromis** [comment]
@metal-oopa any updates?

**Comment by moromis** [comment]
Closing for now, we should re-review packages for unused ones and resubmit a new PR or update this one.

**Pull request closed without merging**
